"""Module containing room ID mappings for Undertale.

## NOTE:
The data in this file is generated from room_ids.csv, which does not belong to me. It was exported and formatted from a Google Sheets document I found in this reddit post: https://www.reddit.com/r/Undertale/comments/3niztd/undertale_room_ids_wip_spoilers/
"""  # noqa

# The following code was used to extract the room ids from the `room_ids.csv` file.
# I'm gonna keep it here in case I need it later for item ids or something 🤷

"""import csv
from pathlib import Path
from pprint import pprint

ROOM_IDS = {}
ROOMS = []

with open(Path(__file__).parent / "room_ids.csv", newline="", encoding="utf-8") as csvfile:
	reader = csv.reader(csvfile)
	for row in reader:
		if len(row) >= 2:
			ROOMS.append({"id": row[0], "name": row[1], "area": row[2] if len(row) > 2 else ""})

ROOMS = sorted(ROOMS, key=lambda x: int(x["id"]) if x["id"].isdigit() else float("inf"))

pprint(ROOMS)"""

ROOM_IDS = [
	{'area': 'ERROR', 'id': '0', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '1', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '2', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '3', 'name': 'Error Dog'},
	{'area': 'RUINS', 'id': '4', 'name': 'Beginning'},
	{'area': 'RUINS', 'id': '5', 'name': "Flowey's Room"},
	{'area': 'RUINS', 'id': '6', 'name': 'First Hall'},
	{'area': 'RUINS', 'id': '7', 'name': 'First Puzzle'},
	{'area': 'RUINS', 'id': '8', 'name': 'Switch Room'},
	{'area': 'RUINS', 'id': '9', 'name': 'Spike Room'},
	{'area': 'RUINS', 'id': '10', 'name': 'Long Hall 1'},
	{'area': 'RUINS', 'id': '11', 'name': 'Long Hall 2'},
	{'area': 'RUINS', 'id': '12', 'name': 'Leaf Piles'},
	{'area': 'RUINS', 'id': '13', 'name': 'Candy Bowl'},
	{'area': 'RUINS', 'id': '14', 'name': 'Hole Puzzle 1'},
	{'area': 'RUINS', 'id': '15', 'name': 'Rock Puzzle 1'},
	{'area': 'RUINS', 'id': '16', 'name': 'Hole Puzzle 2'},
	{'area': 'RUINS', 'id': '17', 'name': 'Rock Puzzle 2'},
	{'area': 'RUINS', 'id': '18', 'name': 'Mouse SAVE 1'},
	{'area': 'RUINS', 'id': '19', 'name': 'Napstablook'},
	{'area': 'RUINS', 'id': '20', 'name': 'RUINS Bakesale'},
	{'area': 'RUINS', 'id': '21', 'name': 'Froggit Hall'},
	{'area': 'RUINS', 'id': '22', 'name': 'Hole Puzzle 3'},
	{'area': 'RUINS', 'id': '23', 'name': 'Color Puzzle 1'},
	{'area': 'RUINS', 'id': '24', 'name': 'Color Puzzle 2'},
	{'area': 'RUINS', 'id': '25', 'name': 'Color Puzzle 3'},
	{'area': 'RUINS', 'id': '26', 'name': 'Color Puzzle 4'},
	{'area': 'RUINS', 'id': '27', 'name': 'Color Puzzle Fail'},
	{'area': 'RUINS', 'id': '28', 'name': 'Road Fork'},
	{'area': 'RUINS', 'id': '29', 'name': 'Froggit Alley'},
	{'area': 'RUINS', 'id': '30', 'name': 'Toy Knife'},
	{'area': 'RUINS', 'id': '31', 'name': 'Home'},
	{'area': 'RUINS', 'id': '32', 'name': 'Home Walkway'},
	{'area': 'RUINS', 'id': '33', 'name': 'Home Living Room'},
	{'area': 'RUINS', 'id': '34', 'name': 'Home Hallway'},
	{'area': 'RUINS', 'id': '35', 'name': "Toriel's Room"},
	{'area': 'RUINS', 'id': '36', 'name': 'Guest Room'},
	{'area': 'RUINS', 'id': '37', 'name': 'Kitchen'},
	{'area': 'RUINS', 'id': '38', 'name': 'Basement Hall 1'},
	{'area': 'RUINS', 'id': '39', 'name': 'Basement Hall 2'},
	{'area': 'RUINS', 'id': '40', 'name': 'Basement Hall 3'},
	{'area': 'RUINS', 'id': '41', 'name': 'Basement Exit'},
	{'area': 'RUINS', 'id': '42', 'name': 'Basement Hall 4'},
	{'area': 'RUINS', 'id': '43', 'name': 'RUINS Exit'},
	{'area': 'Snowdin', 'id': '44', 'name': 'Snowdin Entrance'},
	{'area': 'Snowdin', 'id': '45', 'name': "Sans' Station"},
	{'area': 'Snowdin', 'id': '46', 'name': 'Snowdin Fork 1'},
	{'area': 'Snowdin', 'id': '47', 'name': 'Fishing Rod'},
	{'area': 'Snowdin', 'id': '48', 'name': "Papyrus' Station"},
	{'area': 'Snowdin', 'id': '49', 'name': "Doggo's Station"},
	{'area': 'Snowdin', 'id': '50', 'name': 'Ice Room'},
	{'area': 'Snowdin', 'id': '51', 'name': 'Snowman'},
	{'area': 'Snowdin', 'id': '52', 'name': 'Invisible Walls'},
	{'area': 'Snowdin', 'id': '53', 'name': 'BALL Room'},
	{'area': 'Snowdin', 'id': '54', 'name': "Dogi's Houses"},
	{'area': 'Snowdin', 'id': '55', 'name': 'Crossword Puzzle'},
	{'area': 'Snowdin', 'id': '56', 'name': 'Mouse SAVE 2'},
	{'area': 'Snowdin', 'id': '57', 'name': 'Dogi + Puzzle'},
	{'area': 'Snowdin', 'id': '58', 'name': 'X/O Puzzle 1'},
	{'area': 'Snowdin', 'id': '59', 'name': 'X/O Puzzle 2'},
	{'area': 'Snowdin', 'id': '60', 'name': '"Random" Puzzle'},
	{'area': 'Snowdin', 'id': '61', 'name': 'Snowdog Room'},
	{'area': 'Snowdin', 'id': '62', 'name': 'Ice X/O Fail'},
	{'area': 'Snowdin', 'id': '63', 'name': 'Ice X/O Puzzle'},
	{'area': 'Snowdin', 'id': '64', 'name': 'Snowy Cliff'},
	{'area': 'Snowdin', 'id': '65', 'name': 'Entrance to Cave'},
	{'area': 'Snowdin', 'id': '66', 'name': 'Snow Poff Room'},
	{'area': 'Snowdin', 'id': '67', 'name': 'Bridge to Snowdin'},
	{'area': 'Snowdin', 'id': '68', 'name': 'Snowdin'},
	{'area': 'Snowdin', 'id': '69', 'name': 'Ice Wolf'},
	{'area': 'Snowdin', 'id': '70', 'name': 'Snowdin Ferry'},
	{'area': 'Snowdin', 'id': '71', 'name': 'Inn 1'},
	{'area': 'Snowdin', 'id': '72', 'name': 'Inn 2'},
	{'area': 'Snowdin', 'id': '73', 'name': "Grillby's"},
	{'area': 'Snowdin', 'id': '74', 'name': 'Library'},
	{'area': 'Snowdin', 'id': '75', 'name': 'Garage'},
	{'area': 'Snowdin', 'id': '76', 'name': 'Skeleton House'},
	{'area': 'Snowdin', 'id': '77', 'name': "Papyrus' Room"},
	{'area': 'ERROR', 'id': '78', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '79', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '80', 'name': 'Error Dog'},
	{'area': 'Snowdin', 'id': '81', 'name': 'Foggy Path'},
	{'area': 'Waterfall', 'id': '82', 'name': 'Cave to Waterfall'},
	{'area': 'Waterfall', 'id': '83', 'name': "Sans' WF Station"},
	{'area': 'Waterfall', 'id': '84', 'name': 'Waterfall Box 1'},
	{'area': 'Waterfall', 'id': '85', 'name': 'Dusty Tutu'},
	{'area': 'Waterfall', 'id': '86', 'name': 'Undyne Encounter 1'},
	{'area': 'Waterfall', 'id': '87', 'name': 'Bridge Seeds 1'},
	{'area': 'Waterfall', 'id': '88', 'name': 'Bridge Seeds 2'},
	{'area': 'Waterfall', 'id': '89', 'name': 'Abandoned Quiche'},
	{'area': 'Waterfall', 'id': '90', 'name': 'Wishing Room'},
	{'area': 'Waterfall', 'id': '91', 'name': 'Ancient Writing Hall 1'},
	{'area': 'Waterfall', 'id': '92', 'name': 'Undyne Path 1'},
	{'area': 'Waterfall', 'id': '93', 'name': 'Undyne Encounter 2'},
	{'area': 'Waterfall', 'id': '94', 'name': 'Mouse SAVE 3'},
	{'area': 'Waterfall', 'id': '95', 'name': 'Waterfall Box 2'},
	{'area': 'Waterfall', 'id': '96', 'name': 'Waterfall Nice Cream'},
	{'area': 'Waterfall', 'id': '97', 'name': 'Waterfall Path 1'},
	{'area': 'Waterfall', 'id': '98', 'name': 'Ballet Shoes'},
	{'area': 'Waterfall', 'id': '99', 'name': 'Bird'},
	{'area': 'Waterfall', 'id': '100', 'name': 'Onionsan'},
	{'area': 'Waterfall', 'id': '101', 'name': "Shyren's Room"},
	{'area': 'Waterfall', 'id': '102', 'name': 'Piano Room'},
	{'area': 'Waterfall', 'id': '103', 'name': 'Ancient Artifact'},
	{'area': 'Waterfall', 'id': '104', 'name': 'Ancient Statue'},
	{'area': 'Waterfall', 'id': '105', 'name': 'Umbrella Dispenser'},
	{'area': 'Waterfall', 'id': '106', 'name': 'Rainy Path 1'},
	{'area': 'Waterfall', 'id': '107', 'name': 'Rainy Path 2'},
	{'area': 'Waterfall', 'id': '108', 'name': 'Castle View'},
	{'area': 'Waterfall', 'id': '109', 'name': 'Umbrella Return'},
	{'area': 'Waterfall', 'id': '110', 'name': 'Ancient Writing Hall 2'},
	{'area': 'Waterfall', 'id': '111', 'name': 'Undyne Path 2'},
	{'area': 'Waterfall', 'id': '112', 'name': 'Undyne Path 3'},
	{'area': 'Waterfall', 'id': '113', 'name': 'Garbage Dump 1'},
	{'area': 'Waterfall', 'id': '114', 'name': 'Garbage Dump 2'},
	{'area': 'Waterfall', 'id': '115', 'name': 'Garbage Dump 3'},
	{'area': 'Waterfall', 'id': '116', 'name': 'Quiet Area'},
	{'area': 'Waterfall', 'id': '117', 'name': "Undyne's House Entrance"},
	{'area': 'Waterfall', 'id': '118', 'name': "Undyne's House"},
	{'area': 'Waterfall', 'id': '119', 'name': 'Ghost Houses'},
	{'area': 'Waterfall', 'id': '120', 'name': "Napstablook's House"},
	{'area': 'Waterfall', 'id': '121', 'name': "Mettaton's House"},
	{'area': 'Waterfall', 'id': '122', 'name': 'Blook Family Farm'},
	{'area': 'Waterfall', 'id': '123', 'name': '  ? ? ? ? ? ? ? ?   '},
	{'area': 'Waterfall', 'id': '124', 'name': 'Waterfall Shop'},
	{'area': 'Waterfall', 'id': '125', 'name': 'Waterfall Ferry'},
	{'area': 'Waterfall', 'id': '126', 'name': 'Dual Waterfalls'},
	{'area': 'Waterfall', 'id': '127', 'name': 'Mushroom Maze'},
	{'area': 'Waterfall', 'id': '128', 'name': 'Temmie Village'},
	{'area': 'Waterfall', 'id': '129', 'name': 'Lantern Maze'},
	{'area': 'Waterfall', 'id': '130', 'name': 'Undyne Encounter 3'},
	{'area': 'Waterfall', 'id': '131', 'name': 'Prophecy Room'},
	{'area': 'Waterfall', 'id': '132', 'name': 'Waterfall Bridge'},
	{'area': 'Waterfall', 'id': '133', 'name': 'Connecting Room'},
	{'area': 'Waterfall', 'id': '134', 'name': 'Undyne Arena'},
	{'area': 'Waterfall', 'id': '135', 'name': 'Tunnel to Hotland'},
	{'area': 'Hotland', 'id': '136', 'name': 'Hotland Entrance'},
	{'area': 'Hotland', 'id': '137', 'name': "Sans' Station (Hotland)"},
	{'area': 'Hotland', 'id': '138', 'name': 'Water Cooler'},
	{'area': 'Hotland', 'id': '139', 'name': 'Lab Entrance'},
	{'area': 'Hotland', 'id': '140', 'name': 'Hotland Ferry'},
	{'area': 'Hotland', 'id': '141', 'name': "Alphys' Lab"},
	{'area': 'Hotland', 'id': '142', 'name': "Alphys' Lab Upper"},
	{'area': 'Hotland', 'id': '143', 'name': 'Hotland Pathway 1'},
	{'area': 'Hotland', 'id': '144', 'name': 'Conveyer Belt 1'},
	{'area': 'Hotland', 'id': '145', 'name': 'Magma Zone'},
	{'area': 'Hotland', 'id': '146', 'name': 'Burnt Pan'},
	{'area': 'Hotland', 'id': '147', 'name': 'Laser Puzzle'},
	{'area': 'Hotland', 'id': '148', 'name': 'Puzzle Fork 1'},
	{'area': 'Hotland', 'id': '149', 'name': 'Path to Puzzle Leftt'},
	{'area': 'Hotland', 'id': '150', 'name': 'Shot Puzzle Left'},
	{'area': 'Hotland', 'id': '151', 'name': 'Path to Puzzle Right'},
	{'area': 'Hotland', 'id': '152', 'name': 'Shot Puzzle Right'},
	{'area': 'Hotland', 'id': '153', 'name': 'Path to CWaKR'},
	{'area': 'Hotland', 'id': '154', 'name': 'Cooking With A Killer Robot'},
	{'area': 'Hotland', 'id': '155', 'name': 'CORE View 1'},
	{'area': 'Hotland', 'id': '156', 'name': 'R1 Elevator Door'},
	{'area': 'Hotland', 'id': '157', 'name': 'R2 Elevator Door'},
	{'area': 'Hotland', 'id': '158', 'name': "Sans' Hot Dog Stand"},
	{'area': 'Hotland', 'id': '159', 'name': 'Hotland 3/4-way'},
	{'area': 'Hotland', 'id': '160', 'name': 'Art Club'},
	{'area': 'Hotland', 'id': '161', 'name': 'Stained Apron'},
	{'area': 'Hotland', 'id': '162', 'name': 'Timing Puzzle'},
	{'area': 'Hotland', 'id': '163', 'name': 'Steam Puzzle 1'},
	{'area': 'Hotland', 'id': '164', 'name': 'Bad Opinion Zone'},
	{'area': 'Hotland', 'id': '165', 'name': 'RG01/RG02'},
	{'area': 'Hotland', 'id': '166', 'name': 'Live Report'},
	{'area': 'Hotland', 'id': '167', 'name': 'CORE View 2'},
	{'area': 'Hotland', 'id': '168', 'name': 'L2 Elevator Door'},
	{'area': 'Hotland', 'id': '169', 'name': 'L3 Elevator Door'},
	{'area': 'Hotland', 'id': '170', 'name': 'Spider Parlor'},
	{'area': 'Hotland', 'id': '171', 'name': 'Steam Puzzle 2'},
	{'area': 'Hotland', 'id': '172', 'name': 'Path to Puzzle Down'},
	{'area': 'Hotland', 'id': '173', 'name': 'Shot Puzzle Down'},
	{'area': 'Hotland', 'id': '174', 'name': 'Path to Puzzle Up'},
	{'area': 'Hotland', 'id': '175', 'name': 'Shot Puzzle Up'},
	{'area': 'Hotland', 'id': '176', 'name': 'Spider Entrance'},
	{'area': 'Hotland', 'id': '177', 'name': 'Spiderweb'},
	{'area': 'Hotland', 'id': '178', 'name': 'Spider Exit'},
	{'area': 'Hotland', 'id': '179', 'name': 'Undertale - The Musical'},
	{'area': 'Hotland', 'id': '180', 'name': '"Random" Puzzle Hotland'},
	{'area': 'Hotland', 'id': '181', 'name': 'Hotland Nice Cream '},
	{'area': 'Hotland', 'id': '182', 'name': 'Hotel Entrance'},
	{'area': 'Hotland', 'id': '183', 'name': 'Hotel Lobby'},
	{'area': 'Hotland', 'id': '184', 'name': 'Hotel Resturaunt'},
	{'area': 'Hotland', 'id': '185', 'name': 'Hotel Hallway'},
	{'area': 'Hotland', 'id': '186', 'name': 'Hotel Room'},
	{'area': 'Hotland', 'id': '187', 'name': 'R3 Elevator Door'},
	{'area': 'CORE', 'id': '188', 'name': 'CORE Entrance'},
	{'area': 'CORE', 'id': '189', 'name': 'CORE Lower Elevator'},
	{'area': 'CORE', 'id': '190', 'name': 'Flaming Pit'},
	{'area': 'CORE', 'id': '191', 'name': 'CORE Hall 1'},
	{'area': 'CORE', 'id': '192', 'name': 'CORE Lasers 1'},
	{'area': 'CORE', 'id': '193', 'name': 'CORE Crossroads'},
	{'area': 'CORE', 'id': '194', 'name': 'CORE Ambush'},
	{'area': 'CORE', 'id': '195', 'name': 'CORE Lasers 2'},
	{'area': 'CORE', 'id': '196', 'name': 'CORE Branch'},
	{'area': 'CORE', 'id': '197', 'name': 'CORE West Lower'},
	{'area': 'CORE', 'id': '198', 'name': 'CORE West Mid'},
	{'area': 'CORE', 'id': '199', 'name': 'CORE West Upper'},
	{'area': 'CORE', 'id': '200', 'name': 'CORE North Upper'},
	{'area': 'CORE', 'id': '201', 'name': 'CORE East Upper'},
	{'area': 'CORE', 'id': '202', 'name': 'CORE East Mid'},
	{'area': 'CORE', 'id': '203', 'name': 'CORE East Lower'},
	{'area': 'CORE', 'id': '204', 'name': 'CORE North Mid'},
	{'area': 'CORE', 'id': '205', 'name': 'CORE Shot Puzzle'},
	{'area': 'CORE', 'id': '206', 'name': 'CORE West Trash'},
	{'area': 'CORE', 'id': '207', 'name': 'CORE East trash'},
	{'area': 'CORE', 'id': '208', 'name': 'CORE Battle Path'},
	{'area': 'CORE', 'id': '209', 'name': 'CORE End'},
	{'area': 'CORE', 'id': '210', 'name': 'CORE Upper Elevator'},
	{'area': 'CORE', 'id': '211', 'name': "Mettaton's Stage"},
	{'area': 'CORE', 'id': '212', 'name': 'Path to Long Elevator'},
	{'area': 'CORE', 'id': '213', 'name': 'Hotland Elevator Interior'},
	{'area': 'CORE', 'id': '214', 'name': 'L1 Elevator Door'},
	{'area': 'CORE', 'id': '215', 'name': 'Long Elevator Interior'},
	{'area': 'New Home', 'id': '216', 'name': 'Castle Elevator'},
	{'area': 'New Home', 'id': '217', 'name': 'Backstory Path'},
	{'area': 'New Home', 'id': '218', 'name': 'New Home Path'},
	{'area': 'New Home', 'id': '219', 'name': 'New Home'},
	{'area': 'New Home', 'id': '220', 'name': 'Walkway'},
	{'area': 'New Home', 'id': '221', 'name': 'Living Room'},
	{'area': 'New Home', 'id': '222', 'name': 'Hallway'},
	{'area': 'New Home', 'id': '223', 'name': "Asgore's Room"},
	{'area': 'New Home', 'id': '224', 'name': "Kids' Room"},
	{'area': 'New Home', 'id': '225', 'name': 'Kitchen'},
	{'area': 'New Home', 'id': '226', 'name': 'Basement Hall 1'},
	{'area': 'New Home', 'id': '227', 'name': 'Basement Hall 2'},
	{'area': 'New Home', 'id': '228', 'name': 'Basement Hall 3 '},
	{'area': 'New Home', 'id': '229', 'name': 'Basement Hall 4'},
	{'area': 'New Home', 'id': '230', 'name': 'Basement Hall 5'},
	{'area': 'New Home', 'id': '231', 'name': 'Last Corridor'},
	{'area': 'New Home', 'id': '232', 'name': 'Throne Entrance'},
	{'area': 'New Home', 'id': '233', 'name': 'Stairway'},
	{'area': 'New Home', 'id': '234', 'name': 'Coffins'},
	{'area': 'New Home', 'id': '235', 'name': 'Throne Room'},
	{'area': 'New Home', 'id': '236', 'name': 'The End'},
	{'area': 'New Home', 'id': '237', 'name': 'Barrier'},
	{'area': 'New Home', 'id': '238', 'name': 'Ending'},
	{'area': 'ERROR', 'id': '239', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '240', 'name': 'Error Dog'},
	{'area': 'ERROR', 'id': '241', 'name': 'Error Dog'},
	{'area': 'True Lab', 'id': '242', 'name': "Alphys' Secret Elevator"},
	{'area': 'True Lab', 'id': '243', 'name': 'Crashed Elevator Interior'},
	{'area': 'True Lab', 'id': '244', 'name': 'True Lab Entrance'},
	{'area': 'True Lab', 'id': '245', 'name': 'Path to True Lab'},
	{'area': 'True Lab', 'id': '246', 'name': 'True Lab Lobby'},
	{'area': 'True Lab', 'id': '247', 'name': 'Hall to Operating Room'},
	{'area': 'True Lab', 'id': '248', 'name': 'Operating Room'},
	{'area': 'True Lab', 'id': '249', 'name': 'Red Lock Room'},
	{'area': 'True Lab', 'id': '250', 'name': 'True Lab Hall'},
	{'area': 'True Lab', 'id': '251', 'name': 'True Lab Ward'},
	{'area': 'True Lab', 'id': '252', 'name': 'Golden Flower Room'},
	{'area': 'True Lab', 'id': '253', 'name': 'Blue Lock Room'},
	{'area': 'True Lab', 'id': '254', 'name': 'True Lab Crossroads'},
	{'area': 'True Lab', 'id': '255', 'name': 'Shower Room'},
	{'area': 'True Lab', 'id': '256', 'name': 'Lemon Bread'},
	{'area': 'True Lab', 'id': '257', 'name': 'Yellow Lock Room (Tapes)'},
	{'area': 'True Lab', 'id': '258', 'name': 'True Lab Freezer'},
	{'area': 'True Lab', 'id': '259', 'name': 'Green Lock Room'},
	{'area': 'True Lab', 'id': '260', 'name': 'Fan Room'},
	{'area': 'True Lab', 'id': '261', 'name': 'True Lab Elevator Interior'},
	{'area': 'True Lab', 'id': '262', 'name': 'Hall to Generator'},
	{'area': 'True Lab', 'id': '263', 'name': 'Power Generator'},
	{'area': 'Secret', 'id': '264', 'name': 'Entry Seventeen'},
	{'area': 'Secret', 'id': '265', 'name': "Glyde's Room / Dev Door"},
]
